version: '3.8'

services:
  database:
    container_name: database
    image: "postgres:15-alpine"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: httpserver
      PG_DATA: "database:/data/postgres"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - database:/data/postgres
    restart: always
    networks:
      - http-network

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/httpserver
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - database
    networks:
      - http-network
    ports:
      - "8080:8080" 

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com    # Укажите email для входа в pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin             # Укажите пароль для входа в pgAdmin
    ports:
      - "5050:80"                                 # Открываем порт для доступа к pgAdmin
    networks:
      - http-network

volumes:
  database:

networks:
  http-network:
    driver: bridge
