version: '3.8'

services:
  database:
    container_name: database
    image: "postgres:15-alpine"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: httpserver
      PG_DATA: "database:/data/postgres"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - database:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - http-network

volumes:
  database:

networks:
  http-network:
    driver: bridge